// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNDjoAJYd0Vp95QINyEq4ja8GkIS0WFEE',
    appId: '1:673253843786:web:ce7e6164767866ae8517b3',
    messagingSenderId: '673253843786',
    projectId: 'scoutlink-ba6fb',
    authDomain: 'scoutlink-ba6fb.firebaseapp.com',
    storageBucket: 'scoutlink-ba6fb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkzlu3cVj-EZhdq42VRA0uw--nMMQPfiQ',
    appId: '1:673253843786:android:bf44211b377a9e498517b3',
    messagingSenderId: '673253843786',
    projectId: 'scoutlink-ba6fb',
    storageBucket: 'scoutlink-ba6fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_cCGmnl8siPsKNNqvKc8KAOha5Wl9ggc',
    appId: '1:673253843786:ios:73bc383bbce660678517b3',
    messagingSenderId: '673253843786',
    projectId: 'scoutlink-ba6fb',
    storageBucket: 'scoutlink-ba6fb.firebasestorage.app',
    iosBundleId: 'com.example.scoutlink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_cCGmnl8siPsKNNqvKc8KAOha5Wl9ggc',
    appId: '1:673253843786:ios:73bc383bbce660678517b3',
    messagingSenderId: '673253843786',
    projectId: 'scoutlink-ba6fb',
    storageBucket: 'scoutlink-ba6fb.firebasestorage.app',
    iosBundleId: 'com.example.scoutlink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNDjoAJYd0Vp95QINyEq4ja8GkIS0WFEE',
    appId: '1:673253843786:web:722b11d3397cdb638517b3',
    messagingSenderId: '673253843786',
    projectId: 'scoutlink-ba6fb',
    authDomain: 'scoutlink-ba6fb.firebaseapp.com',
    storageBucket: 'scoutlink-ba6fb.firebasestorage.app',
  );
}
